;;; syzygy-launch-test.el --- New Chat launch contract -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'map)
(require 'json)
(defvar mr-x/agent-shell-presets)
(add-to-list 'load-path (file-name-directory (or load-file-name buffer-file-name)))
(require 'syzygy-bridge)
(when (locate-library "syzygy-launch") (require 'syzygy-launch))

(defun syzygy-launch-test--decode (encoded)
  (json-parse-string (syzygy-bridge-decode-base64 encoded)
                     :object-type 'alist :array-type 'list :false-object :false))

(defun syzygy-launch-test--agent ()
  '((id . "codex") (name . "Codex")
    (models . [((id . "sol") (name . "Sol")) ((id . "astra") (name . "Astra"))])
    (modes . [((id . "agent") (name . "Agent"))])
    (efforts . [((id . "high") (name . "High"))])
    (defaults . ((model . "sol") (mode . "agent") (effort . "")))))

(ert-deftest syzygy-launch-skips-buffers-without-shell-state ()
  "A scratch buffer in agent mode must not hide healthy launch choices."
  (with-temp-buffer
    (let ((broken (current-buffer))
          (mr-x/agent-shell-presets nil)
          (syzygy-launch--capabilities (make-hash-table :test #'equal)))
      (with-temp-buffer
        (let ((healthy (current-buffer)))
          (cl-letf (((symbol-function 'buffer-list) (lambda () (list broken healthy)))
                    ((symbol-function 'derived-mode-p) (lambda (&rest _) t))
                    ((symbol-function 'agent-shell--resolve-preferred-config) (lambda () nil))
                    ((symbol-function 'agent-shell--state)
                     (lambda ()
                       (if (eq (current-buffer) broken)
                           (error "No shell state available")
                         '((:session . ((:id . "ready")))
                           (:agent-config . ((:identifier . codex) (:mode-line-name . "Codex")))))))
                    ((symbol-function 'syzygy-launch--state-options)
                     (lambda (_) '((models . [((id . "sol"))]) (modes . []) (efforts . [])))))
            (let ((agents (alist-get 'agents
                                    (syzygy-launch-test--decode (syzygy-launch-options-json)))))
              (should (equal (mapcar (lambda (a) (alist-get 'id a)) agents) '("codex")))
              (should (equal (alist-get 'id (car (alist-get 'models (car agents)))) "sol")))))))))

(ert-deftest syzygy-launch-opencode-preset-works-without-a-live-chat ()
  "A cold daemon can offer and validate OpenCode through its rig preset."
  (let ((mr-x/agent-shell-presets
         '((?O "OpenCode Luna Build" "openai/gpt-5.6-luna" "build"
               agent-shell-opencode-make-agent-config)))
        (syzygy-launch--capabilities (make-hash-table :test #'equal))
        (syzygy-launch--cli-models (make-hash-table :test #'equal)))
    (cl-letf (((symbol-function 'buffer-list) (lambda () nil))
              ((symbol-function 'agent-shell--resolve-preferred-config) (lambda () nil))
              ((symbol-function 'agent-shell-opencode-make-agent-config)
               (lambda () '((:identifier . opencode) (:mode-line-name . "OpenCode"))))
              ((symbol-function 'syzygy-launch--opencode-cli-output) (lambda () nil)))
      (let* ((reply (syzygy-launch-test--decode (syzygy-launch-options-json)))
             (agents (alist-get 'agents reply))
             (presets (syzygy-launch-test--decode (syzygy-presets-json))))
        (should (equal (alist-get 'agent (car presets)) "opencode"))
        (should (equal (mapcar (lambda (a) (alist-get 'id a)) agents) '("opencode")))
        (should (syzygy-launch--validate
                 '((agent . "opencode") (model . "openai/gpt-5.6-luna") (mode . "build"))
                 agents))
        ;; Live-session capabilities use the config identifier, not the
        ;; constructor's function name. They must enrich the same entry.
        (puthash "opencode"
                 '((models . [((id . "openai/gpt-5.6-luna")) ((id . "openai/gpt-5.6-sol"))])
                   (modes . [((id . "build")) ((id . "plan"))]) (efforts . []))
                 syzygy-launch--capabilities)
        (let ((warm (syzygy-launch--catalog)))
          (should (= (length warm) 1))
          (should (syzygy-launch--validate
                   '((agent . "opencode") (model . "openai/gpt-5.6-sol") (mode . "plan"))
                   warm)))))))

(ert-deftest syzygy-launch-opencode-cli-fills-models-when-no-chat-is-live ()
  "Without a live OpenCode chat, the catalogue lists the CLI's models."
  (let ((mr-x/agent-shell-presets
         '((?O "OpenCode Luna Build" "openai/gpt-5.6-luna" "build"
               agent-shell-opencode-make-agent-config)))
        (syzygy-launch--capabilities (make-hash-table :test #'equal))
        (syzygy-launch--cli-models (make-hash-table :test #'equal))
        (calls 0))
    (cl-letf (((symbol-function 'buffer-list) (lambda () nil))
              ((symbol-function 'agent-shell--resolve-preferred-config) (lambda () nil))
              ((symbol-function 'agent-shell-opencode-make-agent-config)
               (lambda () '((:identifier . opencode) (:mode-line-name . "OpenCode"))))
              ((symbol-function 'syzygy-launch--opencode-cli-output)
               (lambda () (cl-incf calls) "google/gemini-2.5-flash\nopenai/gpt-5.6-luna\n\n")))
      (let* ((agent (car (syzygy-launch--catalog)))
             (ids (mapcar (lambda (m) (alist-get 'id m)) (alist-get 'models agent))))
        (should (equal (alist-get 'source agent) "cli"))
        (should (equal ids '("google/gemini-2.5-flash" "openai/gpt-5.6-luna")))
        ;; The preset's model is already advertised, so it is not appended twice.
        (should (= (length ids) 2))
        (should (equal (alist-get 'id (aref (alist-get 'modes agent) 0)) "build"))
        ;; One subprocess per daemon, not one per catalogue build.
        (syzygy-launch--catalog)
        (should (= calls 1))
        ;; A live session's advertised list still wins over the CLI.
        (puthash "opencode" '((models . [((id . "live/only"))]) (modes . []) (efforts . []))
                 syzygy-launch--capabilities)
        (let ((warm (car (syzygy-launch--catalog))))
          (should (equal (alist-get 'source warm) "advertised"))
          (should (equal (alist-get 'id (aref (alist-get 'models warm) 0)) "live/only")))))))

(ert-deftest syzygy-launch-opencode-cli-failure-falls-back-to-presets ()
  (let ((mr-x/agent-shell-presets
         '((?O "OpenCode Luna Build" "openai/gpt-5.6-luna" "build"
               agent-shell-opencode-make-agent-config)))
        (syzygy-launch--capabilities (make-hash-table :test #'equal))
        (syzygy-launch--cli-models (make-hash-table :test #'equal)))
    (cl-letf (((symbol-function 'buffer-list) (lambda () nil))
              ((symbol-function 'agent-shell--resolve-preferred-config) (lambda () nil))
              ((symbol-function 'agent-shell-opencode-make-agent-config)
               (lambda () '((:identifier . opencode) (:mode-line-name . "OpenCode"))))
              ((symbol-function 'syzygy-launch--opencode-cli-output) (lambda () nil)))
      (let ((agent (car (syzygy-launch--catalog))))
        (should (equal (alist-get 'source agent) "presets"))
        (should (equal (alist-get 'id (aref (alist-get 'models agent) 0)) "openai/gpt-5.6-luna"))))))

(ert-deftest syzygy-launch-validation-rejects-incompatible-settings ()
  (should (fboundp 'syzygy-launch--validate))
  (let ((agents (list (syzygy-launch-test--agent))))
    (should (syzygy-launch--validate
             '((agent . "codex") (model . "astra") (mode . "agent") (effort . "high")) agents))
    (dolist (bad '(((agent . "arbitrary-function") (model . "sol") (mode . "agent"))
                   ((agent . "codex") (model . "sonnet") (mode . "agent"))
                   ((agent . "codex") (model . "sol") (mode . "bypassPermissions"))
                   ((agent . "codex") (model . "sol") (mode . "agent") (effort . "impossible"))))
      (should-error (syzygy-launch--validate bad agents)))))

(ert-deftest syzygy-launch-live-capabilities-include-models-beyond-presets ()
  (should (fboundp 'syzygy-launch--state-options))
  (let ((state '((:session . ((:id . "one"))))))
    (cl-letf (((symbol-function 'agent-shell--get-available-models)
               (lambda (_) '(((:model-id . "astra") (:name . "Astra") (:description . "Advertised")))) )
              ((symbol-function 'agent-shell--get-available-modes)
               (lambda (_) '(((:id . "agent") (:name . "Agent")))))
              ((symbol-function 'agent-shell--config-option-by-category)
               (lambda (_ category)
                 (when (equal category "thought_level")
                   '((:id . "reasoning_effort") (:options . (((:value . "high") (:name . "High")))))))))
      (let ((got (syzygy-launch--state-options state)))
        (should (equal (alist-get 'id (aref (alist-get 'models got) 0)) "astra"))
        (should (equal (alist-get 'id (aref (alist-get 'efforts got) 0)) "high"))))))

(ert-deftest syzygy-launch-invalid-request-never-starts-an-agent ()
  (should (fboundp 'syzygy-launch-json))
  (cl-letf (((symbol-function 'syzygy-launch--catalog)
             (lambda () (list (syzygy-launch-test--agent))))
            ((symbol-function 'agent-shell--start)
             (lambda (&rest _) (ert-fail "Invalid settings reached agent start"))))
    (let ((got (syzygy-launch-test--decode
                (syzygy-launch-json
                 (syzygy-bridge-encode-json
                  '((cwd . "/tmp") (settings . ((agent . "codex") (model . "unknown") (mode . "agent")))))))))
      (should (eq (alist-get 'ok got) :false))
      (should (string-match-p "model" (alist-get 'error got))))))

(ert-deftest syzygy-launch-effort-is-confirmed-before-prompt ()
  (should (fboundp 'syzygy-launch--configure))
  (with-temp-buffer
    (let ((state '((:session . ((:id . "ready"))) (:set-model . t) (:set-session-mode . t)))
          (effort "low") events)
      (cl-letf (((symbol-function 'agent-shell--state) (lambda () state))
                ((symbol-function 'agent-shell--current-model-id) (lambda (_) "sol"))
                ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "agent"))
                ((symbol-function 'agent-shell--config-option-by-category)
                 (lambda (_ _) `((:id . "reasoning_effort") (:current-value . ,effort)
                                  (:options . (((:value . "high")))))))
                ((symbol-function 'agent-shell--set-session-config-option)
                 (lambda (&rest args)
                   (push 'effort events)
                   (setq effort (plist-get args :value))
                   (funcall (plist-get args :on-success))))
                ((symbol-function 'shell-maker-submit)
                 (lambda () (push (buffer-string) events))))
        (syzygy-launch--configure (current-buffer)
                                  '((model . "sol") (mode . "agent") (effort . "high"))
                                  "Do the work")
        (should (equal (nreverse events) '(effort "Do the work")))))))

(ert-deftest syzygy-launch-failed-effort-never-sends-prompt ()
  (should (fboundp 'syzygy-launch--configure))
  (with-temp-buffer
    (cl-letf (((symbol-function 'agent-shell--state)
               (lambda () '((:session . ((:id . "ready"))) (:set-model . t) (:set-session-mode . t))))
              ((symbol-function 'agent-shell--current-model-id) (lambda (_) "sol"))
              ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "agent"))
              ((symbol-function 'agent-shell--config-option-by-category)
               (lambda (_ _) '((:id . "reasoning_effort") (:current-value . "low")
                                (:options . (((:value . "high")))))))
              ((symbol-function 'agent-shell--set-session-config-option)
               (lambda (&rest args) (funcall (plist-get args :on-failure) "Rejected" nil)))
              ((symbol-function 'shell-maker-submit)
               (lambda () (ert-fail "Prompt sent after settings were rejected"))))
      (should-error (syzygy-launch--configure (current-buffer)
                                             '((model . "sol") (mode . "agent") (effort . "high"))
                                             "Do the work")))))

(provide 'syzygy-launch-test)

(ert-deftest syzygy-launch-acknowledged-but-unchanged-effort-never-sends-prompt ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'agent-shell--state)
               (lambda () '((:session . ((:id . "ready"))) (:set-model . t) (:set-session-mode . t))))
              ((symbol-function 'agent-shell--current-model-id) (lambda (_) "sol"))
              ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "agent"))
              ((symbol-function 'agent-shell--config-option-by-category)
               (lambda (_ _) '((:id . "reasoning_effort") (:current-value . "low")
                                (:options . (((:value . "high")))))))
              ((symbol-function 'agent-shell--set-session-config-option)
               (lambda (&rest args) (funcall (plist-get args :on-success))))
              ((symbol-function 'shell-maker-submit)
               (lambda () (ert-fail "Agent acknowledged but did not apply selected effort"))))
      (should-error (syzygy-launch--configure (current-buffer)
                      '((model . "sol") (mode . "agent") (effort . "high")) "Do the work")))))

(ert-deftest syzygy-launch-missing-default-never-selects-first-permission ()
  (let ((syzygy-launch--capabilities (make-hash-table :test #'equal)))
    (puthash "codex" '((models . [((id . "sol") (name . "Sol"))])
                      (modes . [((id . "agent-full-access") (name . "Full access"))])
                      (efforts . [])) syzygy-launch--capabilities)
    (cl-letf (((symbol-function 'buffer-list) (lambda () nil))
              ((symbol-function 'syzygy-launch--configs)
               (lambda () '(("codex" . ((:identifier . codex) (:mode-line-name . "Codex")))))))
      (let ((defaults (alist-get 'defaults (car (syzygy-launch--catalog)))))
        (should (equal (alist-get 'model defaults) ""))
        (should (equal (alist-get 'mode defaults) ""))))))

(ert-deftest syzygy-launch-empty-capabilities-do-not-break-catalogue ()
  (let ((syzygy-launch--capabilities (make-hash-table :test #'equal)))
    (cl-letf (((symbol-function 'buffer-list) (lambda () nil))
              ((symbol-function 'syzygy-launch--configs)
               (lambda () '(("uninitialized" . ((:identifier . uninitialized)))))))
      (let ((agent (car (syzygy-launch--catalog))))
        (should (equal (alist-get 'id agent) "uninitialized"))
        (should (equal (alist-get 'models agent) []))
        (should (equal (alist-get 'modes agent) []))
        (should (equal (alist-get 'mode (alist-get 'defaults agent)) ""))))))

(ert-deftest syzygy-launch-old-claude-drafts-use-advertised-model-ids ()
  "Old phone drafts must launch the intended model, not fail literal equality."
  (dolist (case '(("fable[1m]" "claude-fable-5-1")
                  ("opus[1m]" "opus")))
    (with-temp-buffer
      (let ((sent nil))
        (cl-letf (((symbol-function 'agent-shell--state)
                   (lambda () '((:session . ((:id . "ready")))
                                (:set-model . t) (:set-session-mode . t))))
                  ((symbol-function 'agent-shell--get-available-models)
                   (lambda (_) '(((:model-id . "claude-fable-5-1"))
                                 ((:model-id . "opus")))))
                  ((symbol-function 'agent-shell--current-model-id) (lambda (_) (cadr case)))
                  ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "bypassPermissions"))
                  ((symbol-function 'shell-maker-submit) (lambda () (setq sent (buffer-string)))))
          (syzygy-launch--configure (current-buffer)
                                   `((agent . "claude") (model . ,(car case))
                                     (mode . "bypassPermissions")) "First prompt")
          (should (equal sent "First prompt")))))))

(ert-deftest syzygy-launch-model-resolution-is-agent-scoped-and-preserves-context ()
  (dolist (case '(("claude" "fable[1m]" ("claude-fable-5-1") "claude-fable-5-1")
                  ("claude" "fable[1m]" ("claude-fable-5-1" "claude-fable-5-1[1m]") "claude-fable-5-1[1m]")
                  ("claude" "opus[1m]" ("opus" "opus[1m]") "opus[1m]")
                  ("claude" "claude-fable-5" ("claude-fable-5-1") "claude-fable-5")
                  ("codex" "fable[1m]" ("claude-fable-5-1") "fable[1m]")
                  ("deepseek" "default" ("default") "default")
                  ("opencode" "openai/gpt-6-luna" ("openai/gpt-6-luna") "openai/gpt-6-luna")))
    (should (equal (syzygy-launch--resolve-model
                    (nth 0 case) (nth 1 case)
                    (mapcar (lambda (id) `((id . ,id))) (nth 2 case)))
                   (nth 3 case)))))

(ert-deftest syzygy-launch-applies-settings-before-first-prompt ()
  "A new session starts without defaults; each requested setting must settle."
  (with-temp-buffer
    (let ((model "opus") (mode "default") events
          (state '((:session . ((:id . "ready"))) (:set-model) (:set-session-mode))))
      (cl-letf (((symbol-function 'agent-shell--state) (lambda () state))
                ((symbol-function 'agent-shell--get-available-models)
                 (lambda (_) '(((:model-id . "opus")) ((:model-id . "claude-fable-5-1")))))
                ((symbol-function 'agent-shell--current-model-id) (lambda (_) model))
                ((symbol-function 'agent-shell--current-mode-id) (lambda (_) mode))
                ((symbol-function 'agent-shell--config-option-set-model-id)
                 (lambda (&rest args)
                   (setq model (plist-get args :model-id))
                   (push model events) (funcall (plist-get args :on-success))))
                ((symbol-function 'agent-shell--config-option-set-mode-id)
                 (lambda (&rest args)
                   (setq mode (plist-get args :mode-id))
                   (push mode events) (funcall (plist-get args :on-success))))
                ((symbol-function 'shell-maker-submit) (lambda () (push (buffer-string) events))))
        (syzygy-launch--configure (current-buffer)
                                 '((agent . "claude") (model . "claude-fable-5-1")
                                   (mode . "bypassPermissions")) "First prompt")
        (should (equal (nreverse events)
                       '("claude-fable-5-1" "bypassPermissions" "First prompt")))))))

(ert-deftest syzygy-launch-rejected-model-reports-cause-without-prompt ()
  (with-temp-buffer
    (let ((syzygy-launch--timeout 0))
      (cl-letf (((symbol-function 'agent-shell--state)
                 (lambda () '((:session . ((:id . "ready")))
                              (:set-model . t) (:set-session-mode . t))))
                ((symbol-function 'agent-shell--current-model-id) (lambda (_) "opus"))
                ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "bypassPermissions"))
                ((symbol-function 'agent-shell--config-option-set-model-id)
                 (lambda (&rest args)
                   (funcall (plist-get args :on-failure)
                            '((code . -32603) (message . "Internal error")
                              (data . "Model unavailable for this account")) nil)))
                ((symbol-function 'shell-maker-submit) (lambda () (ert-fail "Sent after rejection"))))
        (let ((err (should-error
                    (syzygy-launch--configure (current-buffer)
                                             '((model . "claude-fable-5-1")
                                               (mode . "bypassPermissions")) "First prompt"))))
          (should (string-match-p "Model unavailable for this account" (error-message-string err)))
          (should (string-empty-p (buffer-string))))))))

(ert-deftest syzygy-launch-late-setting-success-never-sends-prompt ()
  (with-temp-buffer
    (let ((syzygy-launch--timeout 0) callback)
      (cl-letf (((symbol-function 'agent-shell--state)
                 (lambda () '((:session . ((:id . "ready")))
                              (:set-model . t) (:set-session-mode . t))))
                ((symbol-function 'agent-shell--current-model-id) (lambda (_) "opus"))
                ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "bypassPermissions"))
                ((symbol-function 'agent-shell--config-option-set-model-id)
                 (lambda (&rest args) (setq callback (plist-get args :on-success))))
                ((symbol-function 'shell-maker-submit) (lambda () (ert-fail "Late prompt"))))
        (should-error (syzygy-launch--configure
                       (current-buffer) '((model . "claude-fable-5-1")
                                          (mode . "bypassPermissions")) "First prompt"))
        (should (functionp callback))
        (funcall callback)
        (should (string-empty-p (buffer-string)))))))

(ert-deftest syzygy-launch-warm-catalogue-never-invents-preset-options ()
  "A stale preset must not make a rejected model or permission look supported."
  (let ((mr-x/agent-shell-presets '((?f "Fable" "fable[1m]" "obsolete-mode")))
        (syzygy-launch--capabilities (make-hash-table :test #'equal)))
    (puthash "claude" '((models . [((id . "claude-fable-5-1"))])
                        (modes . [((id . "bypassPermissions"))]) (efforts . []))
             syzygy-launch--capabilities)
    (cl-letf (((symbol-function 'buffer-list) (lambda () nil))
              ((symbol-function 'syzygy-launch--configs)
               (lambda () '(("claude" . ((:identifier . claude-code)))))))
      (let* ((agents (syzygy-launch--catalog))
             (settings (syzygy-launch--normalize-settings
                        '((agent . "claude") (model . "fable[1m]")
                          (mode . "bypassPermissions")) agents)))
        (should (equal (alist-get 'model settings) "claude-fable-5-1"))
        ;; The existing phone UI validates stored drafts/pins by choice ID.
        (should (syzygy-launch--known (alist-get 'models (car agents)) "fable[1m]"))
        (should (syzygy-launch--validate settings agents))
        (setf (alist-get 'mode settings) "obsolete-mode")
        (should-error (syzygy-launch--validate settings agents))))))

(ert-deftest syzygy-launch-context-only-catalogue-keeps-bare-preset-usable ()
  (let ((mr-x/agent-shell-presets '((?f "Fable" "claude-fable-5-1" "bypassPermissions")))
        (syzygy-launch--capabilities (make-hash-table :test #'equal)))
    (puthash "claude" '((models . [((id . "claude-fable-5-1[1m]"))])
                        (modes . [((id . "bypassPermissions"))]) (efforts . []))
             syzygy-launch--capabilities)
    (cl-letf (((symbol-function 'buffer-list) (lambda () nil))
              ((symbol-function 'syzygy-launch--configs)
               (lambda () '(("claude" . ((:identifier . claude-code)))))))
      (let* ((agents (syzygy-launch--catalog))
             (settings (syzygy-launch--normalize-settings
                        '((agent . "claude") (model . "claude-fable-5-1")
                          (mode . "bypassPermissions")) agents)))
        (should (syzygy-launch--known (alist-get 'models (car agents)) "claude-fable-5-1"))
        (should (syzygy-launch--validate settings agents))
        (should (equal (syzygy-launch--resolve-model
                        "claude" "claude-fable-5-1"
                        '(((id . "claude-fable-5-1[1m]"))))
                       "claude-fable-5-1[1m]"))))))

(ert-deftest syzygy-launch-permission-mismatch-never-sends-prompt ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'agent-shell--state)
               (lambda () '((:session . ((:id . "ready"))))))
              ((symbol-function 'agent-shell--current-model-id) (lambda (_) "sol"))
              ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "read-only"))
              ((symbol-function 'agent-shell--config-option-set-mode-id)
               (lambda (&rest args) (funcall (plist-get args :on-success))))
              ((symbol-function 'shell-maker-submit) (lambda () (ert-fail "Unconfirmed permissions"))))
      (let ((err (should-error (syzygy-launch--configure
                               (current-buffer) '((model . "sol") (mode . "agent")) "Work"))))
        (should (string-match-p "Permissions mismatch" (error-message-string err)))
        (should (string-empty-p (buffer-string)))))))

(ert-deftest syzygy-launch-startup-timeout-is-distinct-and-never-sends ()
  (with-temp-buffer
    (let ((syzygy-launch--timeout 0))
      (cl-letf (((symbol-function 'agent-shell--state) (lambda () nil))
                ((symbol-function 'shell-maker-submit) (lambda () (ert-fail "Unready session"))))
        (let ((err (should-error (syzygy-launch--configure
                                 (current-buffer) '((model . "sol") (mode . "agent")) "Work"))))
          (should (string-match-p "startup timed out" (error-message-string err))))))))

(ert-deftest syzygy-launch-setting-gets-budget-after-slow-startup ()
  "Startup must not consume the separate model-confirmation deadline."
  (with-temp-buffer
    (let ((clock 0) (syzygy-launch--timeout 2) callback sent (model "old"))
      (cl-letf (((symbol-function 'float-time) (lambda (&optional _) clock))
                ((symbol-function 'accept-process-output)
                 (lambda (&rest _)
                   (cl-incf clock)
                   (when (and callback (= clock 3))
                     (setq model "sol") (funcall callback))))
                ((symbol-function 'agent-shell--state)
                 (lambda () (when (>= clock 2) '((:session . ((:id . "ready")))
                                                (:set-model) (:set-session-mode)))))
                ((symbol-function 'agent-shell--current-model-id) (lambda (_) model))
                ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "agent"))
                ((symbol-function 'agent-shell--config-option-set-model-id)
                 (lambda (&rest args) (setq callback (plist-get args :on-success))))
                ((symbol-function 'shell-maker-submit) (lambda () (setq sent (buffer-string)))))
        (syzygy-launch--configure (current-buffer) '((model . "sol") (mode . "agent")) "Work")
        (should (equal sent "Work"))
        (should (= clock 3))))))

(ert-deftest syzygy-launch-json-old-draft-confirms-canonical-model-and-keeps-recovery ()
  "The HTTP bridge must normalize before validation and retain partial failures."
  (dolist (reject '(nil t))
    (with-temp-buffer
      (let* ((buffer (current-buffer)) (model "opus") sent requested
             (state '((:session . ((:id . "ready"))) (:set-model) (:set-session-mode))))
        (cl-letf (((symbol-function 'syzygy-launch--catalog)
                   (lambda () '(((id . "claude") (name . "Claude")
                                 (models . [((id . "claude-fable-5-1"))])
                                 (modes . [((id . "bypassPermissions"))]) (efforts . [])))))
                  ((symbol-function 'syzygy-launch--configs)
                   (lambda () '(("claude" . ((:identifier . claude-code))))))
                  ((symbol-function 'agent-shell--start)
                   (lambda (&rest args)
                     (should-not (map-elt (plist-get args :config) :default-model-id))
                     (should-not (map-elt (plist-get args :config) :default-session-mode-id))
                     buffer))
                  ((symbol-function 'agent-shell--state) (lambda () state))
                  ((symbol-function 'agent-shell--get-available-models)
                   (lambda (_) '(((:model-id . "claude-fable-5-1")))))
                  ((symbol-function 'agent-shell--current-model-id) (lambda (_) model))
                  ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "bypassPermissions"))
                  ((symbol-function 'agent-shell--config-option-set-model-id)
                   (lambda (&rest args)
                     (setq requested (plist-get args :model-id))
                     (if reject
                         (funcall (plist-get args :on-failure) '((message . "Rejected")) nil)
                       (setq model requested) (funcall (plist-get args :on-success)))))
                  ((symbol-function 'mr-x/agent-label-sync) #'ignore)
                  ((symbol-function 'shell-maker-submit) (lambda () (setq sent (buffer-string)))))
          (let ((reply (syzygy-launch-test--decode
                        (syzygy-launch-json
                         (syzygy-bridge-encode-json
                          `((cwd . ,temporary-file-directory) (task . "First prompt")
                            (settings . ((agent . "claude") (model . "fable[1m]")
                                         (mode . "bypassPermissions")))))))))
            (should (equal requested "claude-fable-5-1"))
            (should (equal (alist-get 'bufferName reply) (buffer-name buffer)))
            (if reject
                (progn (should (eq (alist-get 'ok reply) :false))
                       (should (string-match-p "Rejected" (alist-get 'error reply)))
                       (should-not sent))
              (should (eq (alist-get 'ok reply) t))
              (should (equal sent "First prompt")))))))))

(ert-deftest syzygy-launch-claude-added-context-suffix-is-not-a-failed-launch ()
  "The SDK can publish its 1M spelling only after a successful model switch."
  (with-temp-buffer
    (let ((model "opus") sent
          (state '((:session . ((:id . "ready"))) (:set-model) (:set-session-mode))))
      (cl-letf (((symbol-function 'agent-shell--state) (lambda () state))
                ((symbol-function 'agent-shell--get-available-models)
                 (lambda (_) `(((:model-id . ,(if (equal model "opus")
                                                 "claude-fable-5-1" model))))))
                ((symbol-function 'agent-shell--current-model-id) (lambda (_) model))
                ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "bypassPermissions"))
                ((symbol-function 'agent-shell--config-option-set-model-id)
                 (lambda (&rest args)
                   (should (equal (plist-get args :model-id) "claude-fable-5-1"))
                   (setq model "claude-fable-5-1[1m]")
                   (funcall (plist-get args :on-success))))
                ((symbol-function 'shell-maker-submit) (lambda () (setq sent (buffer-string)))))
        (syzygy-launch--configure (current-buffer)
                                 '((agent . "claude") (model . "claude-fable-5-1")
                                   (mode . "bypassPermissions")) "Work")
        (should (equal sent "Work"))))))

(ert-deftest syzygy-launch-model-comparison-never-substitutes-or-downgrades ()
  (dolist (case '(("claude" "claude-fable-5-1" "claude-fable-5-1[1m]" t)
                  ("claude" "claude-fable-5-1" "claude-fable-5-1-1m" t)
                  ("claude" "claude-fable-5-1[1m]" "claude-fable-5-1" nil)
                  ("claude" "claude-fable-5" "claude-fable-5-1[1m]" nil)
                  ("claude" "claude-fable-5-1" "opus" nil)
                  ("codex" "gpt-6-astra" "gpt-6-astra[1m]" nil)))
    (should (eq (syzygy-launch--model-matches-p
                 (nth 0 case) (nth 1 case) (nth 2 case)) (nth 3 case)))))

(ert-deftest syzygy-launch-later-setting-cannot-silently-change-model ()
  (with-temp-buffer
    (let ((model "sol") (mode "read-only")
          (state '((:session . ((:id . "ready"))) (:set-model) (:set-session-mode))))
      (cl-letf (((symbol-function 'agent-shell--state) (lambda () state))
                ((symbol-function 'agent-shell--current-model-id) (lambda (_) model))
                ((symbol-function 'agent-shell--current-mode-id) (lambda (_) mode))
                ((symbol-function 'agent-shell--config-option-set-mode-id)
                 (lambda (&rest args)
                   (setq mode "agent" model "wrong")
                   (funcall (plist-get args :on-success))))
                ((symbol-function 'shell-maker-submit) (lambda () (ert-fail "Wrong model received prompt"))))
        (should-error (syzygy-launch--configure
                       (current-buffer) '((model . "sol") (mode . "agent")) "Work"))
        (should (string-empty-p (buffer-string)))))))

(ert-deftest syzygy-launch-confirmed-effort-survives-session-restart-config ()
  (with-temp-buffer
    (let* ((config (list (cons :default-config-options nil)))
           (state `((:session . ((:id . "ready"))) (:set-model) (:set-session-mode)
                    (:set-config-options) (:agent-config . ,config))))
      (cl-letf (((symbol-function 'agent-shell--state) (lambda () state))
                ((symbol-function 'agent-shell--current-model-id) (lambda (_) "sol"))
                ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "agent"))
                ((symbol-function 'agent-shell--config-option-by-category)
                 (lambda (_ _) '((:id . "reasoning_effort") (:current-value . "high")
                                  (:options . (((:value . "high"))))))))
        (syzygy-launch--configure (current-buffer)
                                 '((model . "sol") (mode . "agent") (effort . "high")) "")
        (should (equal (funcall (map-elt config :default-config-options))
                       '(("thought_level" . "high"))))))))

(ert-deftest syzygy-launch-legacy-rejection-retains-exact-created-buffer ()
  (with-temp-buffer
    (let ((buffer (current-buffer)))
      (cl-letf (((symbol-function 'mr-x/agent-shell-spawn-for-mobile)
                 (lambda (_cwd _name _task _preset _clone on-created)
                   (funcall on-created buffer)
                   (user-error "Model refused"))))
        (let ((reply (syzygy-launch-test--decode
                      (syzygy-launch-legacy-json
                       (syzygy-bridge-encode-json '((cloneOf . "source")))))))
          (should (eq (alist-get 'ok reply) :false))
          (should (equal (alist-get 'bufferName reply) (buffer-name buffer)))
          (should (string-match-p "Model refused" (alist-get 'error reply))))))))
