;;; syzygy-launch-test.el --- New Chat launch contract -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'map)
(require 'json)
(add-to-list 'load-path (file-name-directory (or load-file-name buffer-file-name)))
(require 'syzygy-bridge)
(when (locate-library "syzygy-launch") (require 'syzygy-launch))

(defun syzygy-launch-test--decode (encoded)
  (json-parse-string (syzygy-bridge-decode-base64 encoded)
                     :object-type 'alist :array-type 'list :false-object :false))

(defun syzygy-launch-test--agent ()
  '((id . "codex") (name . "Codex")
    (models . [((id . "sol") (name . "Sol")) ((id . "astra") (name . "Astra"))])
    (modes . [((id . "agent") (name . "Agent"))])
    (efforts . [((id . "high") (name . "High"))])
    (defaults . ((model . "sol") (mode . "agent") (effort . "")))))

(ert-deftest syzygy-launch-validation-rejects-incompatible-settings ()
  (should (fboundp 'syzygy-launch--validate))
  (let ((agents (list (syzygy-launch-test--agent))))
    (should (syzygy-launch--validate
             '((agent . "codex") (model . "astra") (mode . "agent") (effort . "high")) agents))
    (dolist (bad '(((agent . "arbitrary-function") (model . "sol") (mode . "agent"))
                   ((agent . "codex") (model . "sonnet") (mode . "agent"))
                   ((agent . "codex") (model . "sol") (mode . "bypassPermissions"))
                   ((agent . "codex") (model . "sol") (mode . "agent") (effort . "impossible"))))
      (should-error (syzygy-launch--validate bad agents)))))

(ert-deftest syzygy-launch-live-capabilities-include-models-beyond-presets ()
  (should (fboundp 'syzygy-launch--state-options))
  (let ((state '((:session . ((:id . "one"))))))
    (cl-letf (((symbol-function 'agent-shell--get-available-models)
               (lambda (_) '(((:model-id . "astra") (:name . "Astra") (:description . "Advertised")))) )
              ((symbol-function 'agent-shell--get-available-modes)
               (lambda (_) '(((:id . "agent") (:name . "Agent")))))
              ((symbol-function 'agent-shell--config-option-by-category)
               (lambda (_ category)
                 (when (equal category "thought_level")
                   '((:id . "reasoning_effort") (:options . (((:value . "high") (:name . "High")))))))))
      (let ((got (syzygy-launch--state-options state)))
        (should (equal (alist-get 'id (aref (alist-get 'models got) 0)) "astra"))
        (should (equal (alist-get 'id (aref (alist-get 'efforts got) 0)) "high"))))))

(ert-deftest syzygy-launch-invalid-request-never-starts-an-agent ()
  (should (fboundp 'syzygy-launch-json))
  (cl-letf (((symbol-function 'syzygy-launch--catalog)
             (lambda () (list (syzygy-launch-test--agent))))
            ((symbol-function 'agent-shell--start)
             (lambda (&rest _) (ert-fail "Invalid settings reached agent start"))))
    (let ((got (syzygy-launch-test--decode
                (syzygy-launch-json
                 (syzygy-bridge-encode-json
                  '((cwd . "/tmp") (settings . ((agent . "codex") (model . "unknown") (mode . "agent")))))))))
      (should (eq (alist-get 'ok got) :false))
      (should (string-match-p "model" (alist-get 'error got))))))

(ert-deftest syzygy-launch-effort-is-confirmed-before-prompt ()
  (should (fboundp 'syzygy-launch--configure))
  (with-temp-buffer
    (let ((state '((:session . ((:id . "ready"))) (:set-model . t) (:set-session-mode . t)))
          (effort "low") events)
      (cl-letf (((symbol-function 'agent-shell--state) (lambda () state))
                ((symbol-function 'agent-shell--current-model-id) (lambda (_) "sol"))
                ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "agent"))
                ((symbol-function 'agent-shell--config-option-by-category)
                 (lambda (_ _) `((:id . "reasoning_effort") (:current-value . ,effort)
                                  (:options . (((:value . "high")))))))
                ((symbol-function 'agent-shell--set-session-config-option)
                 (lambda (&rest args)
                   (push 'effort events)
                   (setq effort (plist-get args :value))
                   (funcall (plist-get args :on-success))))
                ((symbol-function 'shell-maker-submit)
                 (lambda () (push (buffer-string) events))))
        (syzygy-launch--configure (current-buffer)
                                  '((model . "sol") (mode . "agent") (effort . "high"))
                                  "Do the work")
        (should (equal (nreverse events) '(effort "Do the work")))))))

(ert-deftest syzygy-launch-failed-effort-never-sends-prompt ()
  (should (fboundp 'syzygy-launch--configure))
  (with-temp-buffer
    (cl-letf (((symbol-function 'agent-shell--state)
               (lambda () '((:session . ((:id . "ready"))) (:set-model . t) (:set-session-mode . t))))
              ((symbol-function 'agent-shell--current-model-id) (lambda (_) "sol"))
              ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "agent"))
              ((symbol-function 'agent-shell--config-option-by-category)
               (lambda (_ _) '((:id . "reasoning_effort") (:current-value . "low")
                                (:options . (((:value . "high")))))))
              ((symbol-function 'agent-shell--set-session-config-option)
               (lambda (&rest args) (funcall (plist-get args :on-failure) "Rejected" nil)))
              ((symbol-function 'shell-maker-submit)
               (lambda () (ert-fail "Prompt sent after settings were rejected"))))
      (should-error (syzygy-launch--configure (current-buffer)
                                             '((model . "sol") (mode . "agent") (effort . "high"))
                                             "Do the work")))))

(provide 'syzygy-launch-test)

(ert-deftest syzygy-launch-acknowledged-but-unchanged-effort-never-sends-prompt ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'agent-shell--state)
               (lambda () '((:session . ((:id . "ready"))) (:set-model . t) (:set-session-mode . t))))
              ((symbol-function 'agent-shell--current-model-id) (lambda (_) "sol"))
              ((symbol-function 'agent-shell--current-mode-id) (lambda (_) "agent"))
              ((symbol-function 'agent-shell--config-option-by-category)
               (lambda (_ _) '((:id . "reasoning_effort") (:current-value . "low")
                                (:options . (((:value . "high")))))))
              ((symbol-function 'agent-shell--set-session-config-option)
               (lambda (&rest args) (funcall (plist-get args :on-success))))
              ((symbol-function 'shell-maker-submit)
               (lambda () (ert-fail "Agent acknowledged but did not apply selected effort"))))
      (should-error (syzygy-launch--configure (current-buffer)
                      '((model . "sol") (mode . "agent") (effort . "high")) "Do the work")))))

(ert-deftest syzygy-launch-missing-default-never-selects-first-permission ()
  (let ((syzygy-launch--capabilities (make-hash-table :test #'equal)))
    (puthash "codex" '((models . [((id . "sol") (name . "Sol"))])
                      (modes . [((id . "agent-full-access") (name . "Full access"))])
                      (efforts . [])) syzygy-launch--capabilities)
    (cl-letf (((symbol-function 'buffer-list) (lambda () nil))
              ((symbol-function 'syzygy-launch--configs)
               (lambda () '(("codex" . ((:identifier . codex) (:mode-line-name . "Codex")))))))
      (let ((defaults (alist-get 'defaults (car (syzygy-launch--catalog)))))
        (should (equal (alist-get 'model defaults) ""))
        (should (equal (alist-get 'mode defaults) ""))))))

(ert-deftest syzygy-launch-empty-capabilities-do-not-break-catalogue ()
  (let ((syzygy-launch--capabilities (make-hash-table :test #'equal)))
    (cl-letf (((symbol-function 'buffer-list) (lambda () nil))
              ((symbol-function 'syzygy-launch--configs)
               (lambda () '(("uninitialized" . ((:identifier . uninitialized)))))))
      (let ((agent (car (syzygy-launch--catalog))))
        (should (equal (alist-get 'id agent) "uninitialized"))
        (should (equal (alist-get 'models agent) []))
        (should (equal (alist-get 'modes agent) []))
        (should (equal (alist-get 'mode (alist-get 'defaults agent)) ""))))))
