;;; mr-x-crash-bundle-test.el --- Immutable bundle store tests -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'json)
(require 'mr-x-crash-bundle)

(defmacro crash-bundle-test--fixture (&rest body)
  (declare (indent 0) (debug t))
  `(let* ((init (file-name-as-directory (file-truename (make-temp-file "bundle-test-" t))))
          (runs (expand-file-name "var/crash-recovery/runs/" init))
          (store (expand-file-name "crash-state/" init)))
     (make-directory runs t)
     (unwind-protect (progn ,@body) (delete-directory init t))))

(defun crash-bundle-test--run (runs init &optional pid clean tag server)
  "Create a run below RUNS for INIT; with PID it is initialized and logged."
  (let ((run (mr-x/crash-run-create runs (or server "sandbox") init))
        (tag (or tag "TAG-1")))
    (when pid
      (let ((identity (mr-x/crash-run-initialized run pid)))
        (mr-x/crash-diagnostics-messages run (format "fixture messages %s\n" tag))
        (mr-x/crash-diagnostics--append run (format "fixture error record %s\n" tag))
        (mr-x/crash-capture--write (expand-file-name "daemon-stderr.log" run)
                                   (format "stderr fixture %s\n" tag) t)
        (when clean (mr-x/crash-run-mark-clean run identity))))
    run))

(defun crash-bundle-test--placement (identity keys)
  (json-encode
   `((schema_version . 1) (source_pid . ,(plist-get identity :pid))
     (source_run . ,(plist-get identity :run-id))
     (frames . ,(vconcat (cl-loop for key in keys for n from 1
                                  collect `((restore_key . ,key) (old_window_id . ,(* 100 n))
                                            (space . ,n) (display . 1))))))))

(defun crash-bundle-test--capture (run pid &optional placement)
  "Commit one two-frame capture in RUN owned by PID; PLACEMENT adds yabai data."
  (let* ((identity (mr-x/crash-run-initialized run pid))
         (session '((:restore-key "frame-a" :window-tree nil)
                    (:restore-key "frame-b" :window-tree nil))))
    (mr-x/crash-capture-save
     run identity (lambda () session)
     (and placement (lambda (frames)
                      (crash-bundle-test--placement
                       identity (mapcar (lambda (f) (plist-get f :restore-key)) frames)))))))

(defun crash-bundle-test--digest (path)
  (mr-x/crash-capture--digest path))

(ert-deftest crash-bundle-unclean-run-becomes-immutable-private-bundle ()
  (crash-bundle-test--fixture
   (let* ((run (crash-bundle-test--run runs init 123))
          (result (mr-x/crash-bundle-process init "sandbox"))
          (id (car (plist-get result :bundled)))
          (bundle (mr-x/crash-bundle-directory store id)))
     (should (= 1 (length (plist-get result :bundled))))
     (should (equal id (mr-x/crash-bundle-active store)))
     (should (file-directory-p bundle))
     (should (= #o700 (logand #o777 (file-modes bundle))))
     (dolist (name '("recent-messages.log" "command-errors.log" "daemon-stderr.log"))
       (should (equal (crash-bundle-test--digest (expand-file-name name run))
                      (crash-bundle-test--digest (expand-file-name name bundle))))
       (should (= #o600 (logand #o777 (file-modes (expand-file-name name bundle))))))
     (let ((manifest (mr-x/crash-capture--read (expand-file-name "manifest.el" bundle)))
           (status (mr-x/crash-bundle-status bundle))
           (report (mr-x/crash-capture--text (expand-file-name "report.log" bundle))))
       (should (equal id (plist-get manifest :bundle-id)))
       (should (equal (file-name-nondirectory run)
                      (plist-get (plist-get manifest :source-run) :run-id)))
       (should (= 123 (plist-get (plist-get manifest :source-run) :pid)))
       (should (eq 'review-only (plist-get status :phase)))
       (should (equal id (plist-get status :bundle-id)))
       (should (string-match-p "TAG-1" report))
       (should (string-match-p "== latest command errors" report))
       (should (string-match-p "== recent messages" report))
       (should (string-match-p "== daemon stderr" report))
       (should-not (string-match-p "correlation incomplete" report)))
     (let ((processed (mr-x/crash-capture--read (expand-file-name "processed.el" run))))
       (should (equal id (plist-get processed :bundle-id)))))))

(ert-deftest crash-bundle-clean-run-is-processed-without-a-bundle ()
  (crash-bundle-test--fixture
   (let* ((run (crash-bundle-test--run runs init 123 'clean))
          (result (mr-x/crash-bundle-process init "sandbox")))
     (should-not (plist-get result :bundled))
     (should-not (mr-x/crash-bundle-active store))
     (should-not (mr-x/crash-bundle-pending store))
     (let ((processed (mr-x/crash-capture--read (expand-file-name "processed.el" run))))
       (should (plist-member processed :bundle-id))
       (should-not (plist-get processed :bundle-id))))))

(ert-deftest crash-bundle-processing-is-idempotent-and-finishes-interrupted-marker ()
  (crash-bundle-test--fixture
   (let* ((run (crash-bundle-test--run runs init 123))
          (id (car (plist-get (mr-x/crash-bundle-process init "sandbox") :bundled)))
          (bundle (mr-x/crash-bundle-directory store id))
          (before (crash-bundle-test--digest (expand-file-name "report.log" bundle))))
     (should-not (plist-get (mr-x/crash-bundle-process init "sandbox") :bundled))
     (delete-file (expand-file-name "processed.el" run))
     (should-not (plist-get (mr-x/crash-bundle-process init "sandbox") :bundled))
     (should (= 1 (length (directory-files (expand-file-name "bundles" store) nil "\\`bundle-"))))
     (should (equal before (crash-bundle-test--digest (expand-file-name "report.log" bundle))))
     (should (equal id (plist-get (mr-x/crash-capture--read (expand-file-name "processed.el" run))
                                  :bundle-id))))))

(ert-deftest crash-bundle-two-unclean-runs-keep-both-and-discard-reveals-older ()
  (crash-bundle-test--fixture
   (let* ((older (crash-bundle-test--run runs init 123 nil "TAG-OLD"))
          (newer (progn (sleep-for 0.01) (crash-bundle-test--run runs init 124 nil "TAG-NEW")))
          (result (mr-x/crash-bundle-process init "sandbox"))
          (old-id (concat "bundle-" (file-name-nondirectory older)))
          (new-id (concat "bundle-" (file-name-nondirectory newer))))
     (should (equal (sort (copy-sequence (plist-get result :bundled)) #'string<)
                    (sort (list old-id new-id) #'string<)))
     (should (equal new-id (mr-x/crash-bundle-active store)))
     (should (equal (list new-id old-id) (mapcar #'car (mr-x/crash-bundle-pending store))))
     (mr-x/crash-bundle-discard store new-id)
     (should (equal old-id (mr-x/crash-bundle-active store)))
     (should-not (file-exists-p (mr-x/crash-bundle-directory store new-id)))
     (should (string-match-p "TAG-OLD" (mr-x/crash-capture--text
                                        (expand-file-name "report.log" (mr-x/crash-bundle-directory store old-id)))))
     (mr-x/crash-bundle-discard store old-id)
     (should-not (mr-x/crash-bundle-active store)))))

(ert-deftest crash-bundle-status-transitions-are-atomic-and-illegal-ones-fail-closed ()
  (crash-bundle-test--fixture
   (let* ((run (crash-bundle-test--run runs init 123)))
     (crash-bundle-test--capture run 123)
     (let* ((id (car (plist-get (mr-x/crash-bundle-process init "sandbox") :bundled)))
            (bundle (mr-x/crash-bundle-directory store id))
            (file (expand-file-name "restore-status.el" bundle))
            (status (mr-x/crash-bundle-status bundle)))
       (should (eq 'pending-frames (plist-get status :phase)))
       (should (= 0 (plist-get status :attempt)))
       (should (= 2 (plist-get status :requested-frame-count)))
       (should-not (plist-get status :owner))
       (should (numberp (plist-get status :updated-at)))
       (should-error (mr-x/crash-bundle-transition bundle 'pending-frames 'complete))
       (should-error (mr-x/crash-bundle-transition bundle 'review-only 'discarded))
       (should (eq 'pending-frames (plist-get (mr-x/crash-bundle-status bundle) :phase)))
       (let ((next (mr-x/crash-bundle-transition bundle 'pending-frames 'restoring-frames
                                                 :owner '(:run-id "r" :pid 5) :attempt 1)))
         (should (eq 'restoring-frames (plist-get next :phase)))
         (should (= 1 (plist-get next :attempt)))
         (should (equal '(:run-id "r" :pid 5) (plist-get (mr-x/crash-bundle-status bundle) :owner))))
       (should-error (mr-x/crash-bundle-transition bundle 'restoring-frames 'complete))
       (should-error (mr-x/crash-bundle-transition bundle 'restoring-frames 'discarded))
       (should-error (mr-x/crash-bundle-transition bundle 'pending-frames 'restoring-frames))
       (mr-x/crash-bundle-transition bundle 'restoring-frames 'cleanup-pending
                                     :residual-resources '("buffer-x"))
       (should-error (mr-x/crash-bundle-transition bundle 'cleanup-pending 'complete))
       (should-error (mr-x/crash-bundle-transition bundle 'cleanup-pending 'discarded))
       (mr-x/crash-bundle-transition bundle 'cleanup-pending 'cleanup-pending :cancel-requested t)
       (mr-x/crash-bundle-transition bundle 'cleanup-pending 'discarded)
       (should (eq 'discarded (plist-get (mr-x/crash-bundle-status bundle) :phase)))
       (should-error (mr-x/crash-bundle-transition bundle 'discarded 'pending-frames))
       (should (= #o600 (logand #o777 (file-modes file))))))))

(ert-deftest crash-bundle-legacy-flat-bundle-is-reported-not-rewritten ()
  (crash-bundle-test--fixture
   (make-directory store t)
   (mr-x/crash-capture--write (expand-file-name "session-state.el" store) '((:restore-key "legacy")))
   (mr-x/crash-capture--write (expand-file-name "stderr.log" store) "legacy stderr\n" t)
   (let ((session (crash-bundle-test--digest (expand-file-name "session-state.el" store)))
         (stderr (crash-bundle-test--digest (expand-file-name "stderr.log" store))))
     (crash-bundle-test--run runs init 123)
     (let ((result (mr-x/crash-bundle-process init "sandbox")))
       (should (mr-x/crash-bundle-legacy-p store))
       (should (= 1 (length (plist-get result :bundled))))
       (should (equal (car (plist-get result :bundled)) (mr-x/crash-bundle-active store)))
       (should (equal session (crash-bundle-test--digest (expand-file-name "session-state.el" store))))
       (should (equal stderr (crash-bundle-test--digest (expand-file-name "stderr.log" store))))))))

(ert-deftest crash-bundle-skips-current-run-and-other-daemons ()
  (crash-bundle-test--fixture
   (let* ((current (crash-bundle-test--run runs init 123))
          (other-server (crash-bundle-test--run runs init 124 nil "TAG-2" "server"))
          (other-init (crash-bundle-test--run runs "/tmp/other-init/" 125))
          (result (mr-x/crash-bundle-process init "sandbox" (file-name-nondirectory current))))
     (should-not (plist-get result :bundled))
     (should-not (mr-x/crash-bundle-active store))
     (dolist (run (list current other-server other-init))
       (should-not (file-exists-p (expand-file-name "processed.el" run)))))))

(ert-deftest crash-bundle-early-start-run-without-pid-is-review-only-and-labeled ()
  (crash-bundle-test--fixture
   (let* ((run (crash-bundle-test--run runs init nil))
          (id (car (plist-get (mr-x/crash-bundle-process init "sandbox") :bundled)))
          (bundle (mr-x/crash-bundle-directory store id)))
     (should id)
     (should (eq 'review-only (plist-get (mr-x/crash-bundle-status bundle) :phase)))
     (should-not (plist-get (plist-get (mr-x/crash-bundle-status bundle) :source-run) :pid))
     (should (string-match-p "correlation incomplete"
                             (mr-x/crash-capture--text (expand-file-name "report.log" bundle))))
     (should (file-exists-p (expand-file-name "processed.el" run))))))

(ert-deftest crash-bundle-committed-capture-makes-bundle-restorable ()
  (crash-bundle-test--fixture
   (let* ((frame-only (crash-bundle-test--run runs init 123))
          (placed (crash-bundle-test--run runs init 124)))
     (crash-bundle-test--capture frame-only 123)
     (crash-bundle-test--capture placed 124 'placement)
     (mr-x/crash-bundle-process init "sandbox")
     (let* ((a (mr-x/crash-bundle-directory store (concat "bundle-" (file-name-nondirectory frame-only))))
            (b (mr-x/crash-bundle-directory store (concat "bundle-" (file-name-nondirectory placed))))
            (capture-a (plist-get (mr-x/crash-capture-current frame-only) :directory))
            (capture-b (plist-get (mr-x/crash-capture-current placed) :directory)))
       (should (equal (crash-bundle-test--digest (expand-file-name "session-state.el" capture-a))
                      (crash-bundle-test--digest (expand-file-name "session-state.el" a))))
       (should-not (file-exists-p (expand-file-name "yabai-state.json" a)))
       (should (eq 'pending-frames (plist-get (mr-x/crash-bundle-status a) :phase)))
       (should-not (plist-get (mr-x/crash-bundle-status a) :yabai-required))
       (should (= 2 (plist-get (mr-x/crash-bundle-status a) :requested-frame-count)))
       (should (equal (crash-bundle-test--digest (expand-file-name "yabai-state.json" capture-b))
                      (crash-bundle-test--digest (expand-file-name "yabai-state.json" b))))
       (should (plist-get (mr-x/crash-bundle-status b) :yabai-required))
       (should (equal (plist-get (mr-x/crash-capture--read (expand-file-name "manifest.el" b)) :capture-id)
                      (plist-get (mr-x/crash-capture-current placed) :capture-id)))))))

(ert-deftest crash-bundle-active-pointer-is-repaired-and-terminal-orphans-cleaned ()
  (crash-bundle-test--fixture
   (crash-bundle-test--run runs init 123 nil "TAG-A")
   (sleep-for 0.01)
   (crash-bundle-test--run runs init 124 nil "TAG-B")
   (let* ((ids (plist-get (mr-x/crash-bundle-process init "sandbox") :bundled))
          (newest (mr-x/crash-bundle-active store))
          (older (car (remove newest ids)))
          (bundles (expand-file-name "bundles" store)))
     (mr-x/crash-capture--write (expand-file-name "active.el" store)
                                '(:schema-version 1 :bundle-id "bundle-missing"))
     (should (equal newest (mr-x/crash-bundle-active store)))
     (delete-file (expand-file-name "active.el" store))
     (should (equal newest (mr-x/crash-bundle-active store)))
     ;; A bundle left terminal by an interrupted consume is finished at startup.
     (mr-x/crash-bundle-transition (mr-x/crash-bundle-directory store newest)
                                   'review-only 'discarded)
     (make-directory (expand-file-name ".bundle-abandoned" bundles))
     (mr-x/crash-bundle-process init "sandbox")
     (should-not (file-exists-p (mr-x/crash-bundle-directory store newest)))
     (should-not (file-exists-p (expand-file-name ".bundle-abandoned" bundles)))
     (should (equal older (mr-x/crash-bundle-active store))))))

(ert-deftest crash-bundle-consume-requires-complete-and-advances-pointer-before-delete ()
  (crash-bundle-test--fixture
   (let ((older (crash-bundle-test--run runs init 123 nil "TAG-A")))
     (sleep-for 0.01)
     (let ((newer (crash-bundle-test--run runs init 124 nil "TAG-B")))
       (crash-bundle-test--capture newer 124)
       (mr-x/crash-bundle-process init "sandbox")
       (let* ((new-id (concat "bundle-" (file-name-nondirectory newer)))
              (old-id (concat "bundle-" (file-name-nondirectory older)))
              (bundle (mr-x/crash-bundle-directory store new-id)))
         (should-error (mr-x/crash-bundle-consume store new-id))
         (should (file-directory-p bundle))
         (mr-x/crash-bundle-transition bundle 'pending-frames 'restoring-frames :attempt 1)
         (mr-x/crash-bundle-transition bundle 'restoring-frames 'pending-yabai
                                       :restored-frames '((:restore-key "frame-a" :window-id nil)
                                                          (:restore-key "frame-b" :window-id nil)))
         (mr-x/crash-bundle-transition bundle 'pending-yabai 'complete)
         (cl-letf (((symbol-function 'delete-directory)
                    (lambda (&rest _) (error "fixture delete failure"))))
           (should-error (mr-x/crash-bundle-consume store new-id))
           (should (equal old-id (mr-x/crash-bundle-active store)))
           (should (file-directory-p bundle)))
         (mr-x/crash-bundle-consume store new-id)
         (should-not (file-directory-p bundle))
         (should (equal old-id (mr-x/crash-bundle-active store))))))))

(ert-deftest crash-bundle-discard-is-refused-while-an-operation-is-active ()
  (crash-bundle-test--fixture
   (let ((run (crash-bundle-test--run runs init 123)))
     (crash-bundle-test--capture run 123)
     (let* ((id (car (plist-get (mr-x/crash-bundle-process init "sandbox") :bundled)))
            (bundle (mr-x/crash-bundle-directory store id)))
       (mr-x/crash-bundle-transition bundle 'pending-frames 'restoring-frames :attempt 1)
       (should-error (mr-x/crash-bundle-discard store id))
       (should (file-directory-p bundle))
       (should (eq 'restoring-frames (plist-get (mr-x/crash-bundle-status bundle) :phase)))
       (should (equal id (mr-x/crash-bundle-active store)))))))

(ert-deftest crash-bundle-report-is-bounded-and-evidence-copied-whole ()
  (crash-bundle-test--fixture
   (let ((run (crash-bundle-test--run runs init 123)))
     (mr-x/crash-capture--write (expand-file-name "command-errors.log" run)
                                (concat (make-string (* 3 1024 1024) ?e) "\nTAIL-MARK\n") t)
     (let* ((id (car (plist-get (mr-x/crash-bundle-process init "sandbox") :bundled)))
            (bundle (mr-x/crash-bundle-directory store id)))
       (should (<= (file-attribute-size (file-attributes (expand-file-name "report.log" bundle)))
                   (* 2 1024 1024)))
       (should (string-match-p "TAIL-MARK" (mr-x/crash-capture--text (expand-file-name "report.log" bundle))))
       (should (equal (crash-bundle-test--digest (expand-file-name "command-errors.log" run))
                      (crash-bundle-test--digest (expand-file-name "command-errors.log" bundle))))))))

(provide 'mr-x-crash-bundle-test)
;;; mr-x-crash-bundle-test.el ends here
