;;; mr-x-crash-runtime-test.el --- Isolated runtime wiring tests -*- lexical-binding: t; -*-
(require 'ert)
(require 'cl-lib)
(require 'server)
(require 'mr-x-crash-runtime)

(defmacro crash-runtime-test--fixture (&rest body)
  (declare (indent 0) (debug t))
  `(let* ((init (file-name-as-directory (file-truename (make-temp-file "runtime-test-" t))))
          (user-emacs-directory init)
          (process-environment (copy-sequence process-environment))
          (noninteractive nil)
          (server-name "sandbox")
          (kill-emacs-hook nil) (emacs-startup-hook nil)
          (command-error-function (lambda (&rest _) 'delegated))
          (mr-x/crash-runtime--identity nil) (mr-x/crash-runtime--directory nil)
          (mr-x/crash-runtime--timer nil) (mr-x/crash-runtime--wrapper nil)
          (mr-x/crash-runtime--previous nil)
          (parent (expand-file-name "var/crash-recovery/runs/" init)))
     (make-directory parent t)
     (let ((run (mr-x/crash-run-create parent "sandbox" init)))
       (setenv "MR_X_EMACS_RUN_DIRECTORY" run)
       (setenv "MR_X_EMACS_RUN_ID" (file-name-nondirectory run))
       (unwind-protect
           (cl-letf (((symbol-function 'daemonp) (lambda () "sandbox"))) ,@body)
         (mr-x/crash-runtime-stop)
         (delete-directory init t)))))

(ert-deftest crash-runtime-batch-and-inert-load-do-not-install ()
  (crash-runtime-test--fixture
   (let ((noninteractive t) (before command-error-function))
     (load "mr-x-crash-runtime" nil t)
     (mr-x/crash-runtime-arm)
     (should-not emacs-startup-hook)
     (should-not (mr-x/crash-runtime-start))
     (should (eq before command-error-function))
     (should-not (plist-get (mr-x/crash-run-metadata run) :pid)))))

(ert-deftest crash-runtime-installs-once-records-pid-logs-and-clean-exit ()
  (crash-runtime-test--fixture
   (mr-x/crash-runtime-arm)
   (should-not mr-x/crash-runtime--identity)
   (run-hooks 'emacs-startup-hook)
   (should (= (emacs-pid) (plist-get (mr-x/crash-run-metadata run) :pid)))
   (let ((timer mr-x/crash-runtime--timer) (wrapper command-error-function))
     (mr-x/crash-runtime-start)
     (should (eq timer mr-x/crash-runtime--timer))
     (should (eq wrapper command-error-function)))
   (should (eq 'delegated (funcall command-error-function '(error "fixture-error") "fixture" 'fixture)))
   (should (file-exists-p (expand-file-name "command-errors.log" run)))
   (should (file-exists-p (expand-file-name "recent-messages.log" run)))
   (run-hooks 'kill-emacs-hook)
   (should (mr-x/crash-run-clean-p run))))

(ert-deftest crash-runtime-rejects-wrong-run-server-and-directory-before-install ()
  (crash-runtime-test--fixture
   (let ((before command-error-function))
     (setenv "MR_X_EMACS_RUN_ID" "stale-run")
     (should-error (mr-x/crash-runtime-start))
     (setenv "MR_X_EMACS_RUN_ID" (file-name-nondirectory run))
     (let ((server-name "server")) (should-error (mr-x/crash-runtime-start)))
     (let ((user-emacs-directory "/tmp/other-init/"))
       (should-error (mr-x/crash-runtime-start)))
     (should (eq before command-error-function))
     (should-not mr-x/crash-runtime--timer)
     (should-not (plist-get (mr-x/crash-run-metadata run) :pid)))))

(ert-deftest crash-runtime-stop-preserves-a-newer-error-handler ()
  (crash-runtime-test--fixture
   (mr-x/crash-runtime-start)
   (let ((new (lambda (&rest _) 'newer)) (timer mr-x/crash-runtime--timer))
     (setq command-error-function new)
     (mr-x/crash-runtime-stop)
     (should (eq new command-error-function))
     (should-not (memq timer timer-list))
     (should-not kill-emacs-hook))))

(ert-deftest crash-runtime-log-failure-does-not-prevent-clean-marker ()
  (crash-runtime-test--fixture
   (mr-x/crash-runtime-start)
   (cl-letf (((symbol-function 'mr-x/crash-diagnostics-messages)
              (lambda (&rest _) (error "fixture disk failure"))))
     (run-hooks 'kill-emacs-hook))
   (should (mr-x/crash-run-clean-p run))))

(ert-deftest crash-runtime-failed-install-removes-partial-wiring ()
  (crash-runtime-test--fixture
   (let ((before command-error-function))
     (cl-letf (((symbol-function 'run-with-timer) (lambda (&rest _) (error "fixture timer failure"))))
       (should-error (mr-x/crash-runtime-start)))
     (should (eq before command-error-function))
     (should-not mr-x/crash-runtime--identity)
     (should-not mr-x/crash-runtime--timer)
     (should-not kill-emacs-hook)
     (mr-x/crash-runtime-start)
     (should mr-x/crash-runtime--identity))))

(provide 'mr-x-crash-runtime-test)
